import * as ReactNamespace from "react";
import ReactDefault from "react";

export default ReactDefault;
export const Children = ReactNamespace.Children;
export const Component = ReactNamespace.Component;
export const Fragment = ReactNamespace.Fragment;
export const Profiler = ReactNamespace.Profiler;
export const PureComponent = ReactNamespace.PureComponent;
export const StrictMode = ReactNamespace.StrictMode;
export const Suspense = ReactNamespace.Suspense;
export const cloneElement = ReactNamespace.cloneElement;
export const createContext = ReactNamespace.createContext;
export const createElement = ReactNamespace.createElement;
export const createRef = ReactNamespace.createRef;
export const forwardRef = ReactNamespace.forwardRef;
export const isValidElement = ReactNamespace.isValidElement;
export const lazy = ReactNamespace.lazy;
export const memo = ReactNamespace.memo;
export const startTransition = ReactNamespace.startTransition;
export const use = ReactNamespace.use;
export const useActionState = ReactNamespace.useActionState;
export const useCallback = ReactNamespace.useCallback;
export const useContext = ReactNamespace.useContext;
export const useDebugValue = ReactNamespace.useDebugValue;
export const useDeferredValue = ReactNamespace.useDeferredValue;
export const useEffect = ReactNamespace.useEffect;
export const useEffectEvent = ReactNamespace.useEffectEvent;
export const useId = ReactNamespace.useId;
export const useImperativeHandle = ReactNamespace.useImperativeHandle;
export const useInsertionEffect = ReactNamespace.useInsertionEffect;
export const useLayoutEffect = ReactNamespace.useLayoutEffect;
export const useMemo = ReactNamespace.useMemo;
export const useOptimistic = ReactNamespace.useOptimistic;
export const useReducer = ReactNamespace.useReducer;
export const useRef = ReactNamespace.useRef;
export const useState = ReactNamespace.useState;
export const useSyncExternalStore = ReactNamespace.useSyncExternalStore;
export const useTransition = ReactNamespace.useTransition;
export const version = ReactNamespace.version;
